[package]
name = "wasm-demo"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "3.0.0-beta.12"
napi-derive = "3.0.0-beta.12"

[build-dependencies]
napi-build = "2.2.2"
